### ISSUE TITLE
fstrim -m 16m?

### ISSUE THREAD

**Issue by daydreamjf** [zzhou1/fstrim-throttle#2]
hi, i want to know why  -m default param is 16m? i found it influence d/s  a lot。 expect answers, thanks

**Comment by zzhou1** [comment]
The current default value is just defined in old days, probably does not fit your case well enough.  Adaptive trimming policies may need to be tailored on a case-by-case basis. The free block distribution quite depends on how fragmented of the filesystem. Also SSD devices becomes cheaper and larger over time for the larger filesystem... etc.

**Comment by daydreamjf** [comment]
thanks， is there any general way to analyze the current situation , and then decide the param? i am worried about that my fstrim way is not effective enough when i set this param a non zero value. In my test, if -m zero, d/s is high (of course, i set -c), but low when i set 512k （most my files is bigger than that）

**Comment by zzhou1** [comment]
What I have in my mind is to leverage the filesystem toolbox to do analysis to understand the histogram of free extent sizes, for example. Please be noted that the different types of filesystem has different tools. It will take some time to understand the workload of your system and find the pattern. Then generate the corresponding policy accordingly.

**Comment by daydreamjf** [comment]
ok，i will have a try, and close this issue
